build: off # Tells AppVeyor to not look for a Visual studio project nor to run arbitraty scripted actions via build_script.

platform: x64

version: '{build}'

clone_folder: c:/wasp # This is where wasp repo will be cloned into.

environment:
  PATH: c:/bin;%PATH%
  STACK_ROOT: c:/stack
  TMP: c:/tmp # https://github.com/haskell/cabal/issues/5386

# `a -> b` means that cached item `a` will be invalidated if `b` changes.
# Important: AppVeyor has 1GB limit on cache for free account.
# TODO: I copied this from rattletrap, figure out if I should change smth
# regarding caching (change dependencies? Add .stack-work?
cache:
  - c:/stack -> waspc/stack.yaml
  - c:/Users/appveyor/AppData/Local/Programs/stack -> waspc/stack.yaml

install:
  - ps: cd waspc
  # Install latest stable stack.
  - ps: |
      curl -OutFile stack.zip -Uri https://get.haskellstack.org/stable/windows-x86_64.zip
      7z x stack.zip stack.exe
      mkdir c:/bin
      mv stack.exe c:/bin

test_script:
  - stack setup > nul # Due it silently due to lot of not very interesting output.
  # Ugly echo "" hack is to avoid complaints about 0 being an invalid file descriptor.
  - echo "" | stack --no-terminal test --only-dependencies
  - echo "" | stack --no-terminal test

after_test:
  - ps: mkdir appveyor-releases/
  - ps: mv "$(stack path --local-install-root)/bin/wasp.exe" "appveyor-releases/wasp-windows.exe"

artifacts:
  - path: wasp/appveyor-releases/wasp-windows.exe
    name: wasp-windows.exe

deploy:
  provider: Github
  auth_token:
    secure: kyc1YtELeuOSAvRQtg6ppmMWYkbsP16z3eBRu09YozknJEXySteOJTHUUyaMocjC
  #description: "Windows exe" # Allegedly this is mandatory? Try without it.
  artifact: wasp-windows.exe
  force_update: true # Adds files to release even if it already exists.
  on:
    APPVEYOR_REPO_TAG: true # Deploy on tag push only.

